### ISSUE TITLE
Seldon <=1.15 does not support k8s 1.25+

### ISSUE THREAD

**Issue by ca-scribner** [canonical/seldon-core-operator#116] opened 2023-03-17 13:11 UTC
The k8s autoscaling/v2beta1 API has been migrated to v2, causing [this issue](https://github.com/SeldonIO/seldon-core/issues/4339) in Seldon and blocking Seldon <=1.15 from using k8s 1.25+.  Seldon 1.16 will fix this and support k8s 1.25+.

**Comment by beliaev-maksim** [comment] 2023-06-23 12:58
v2beta2 is still available in 1.25

maybe there is another issue?

![image](https://github.com/canonical/seldon-core-operator/assets/51964909/79f4a3a7-0af1-4944-a633-4960fcfa527f)

**Comment by ca-scribner** [comment] 2023-06-23 13:27
hmm i haven't tested it myself, but there was enough activity on that thread to think it correct. We could give it a try and see

**Comment by beliaev-maksim** [comment] 2023-06-23 14:06
@ca-scribner 
ok, I see

you did a typo in your description, it is the first version of beta, not second

`autoscaling/v2beta1`

which is indeed removed in 1.25

**Comment by NohaIhab** [comment] 2023-07-21 10:11
Tested and confirmed the issue on microk8s 1.25
```
Status:
  Address:
    URL:  http://iris-model-default.admin.svc.cluster.local:8000/api/v1.0/predictions
  Conditions:
    Last Transition Time:  2023-07-21T09:41:01Z
    Reason:                Not all services created
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-07-21T09:41:01Z
    Reason:                Not all services created
    Status:                False
    Type:                  ServicesReady
  Description:             no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
  State:                   Failed
Events:
  Type     Reason         Age                   From                       Message
  ----     ------         ----                  ----                       -------
  Normal   CreateService  4m24s                 seldon-controller-manager  Created Service "iris-model-default-classifier"
  Normal   CreateService  4m24s                 seldon-controller-manager  Created Service "iris-model-default"
  Warning  UpdateFailed   4m19s                 seldon-controller-manager  Failed to update status for SeldonDeployment "iris-model": Operation cannot be fulfilled on seldondeployments.machinelearning.seldon.io "iris-model": the object has been modified; please apply your changes to the latest version and try again
  Warning  InternalError  78s (x16 over 4m22s)  seldon-controller-manager  no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
```

**Comment by kimwnasptd** [comment] 2023-08-03 14:23
After Noha's confirmation we are closing this issue since Seldon 1.15 is not working with K8s 1.25.

CKF 1.8 should be able to run on K8s 1.25 since it will use Seldon 1.17

**Closed by kimwnasptd** 2023-08-03 14:23 UTC
Labels: bug, enhancement, Kubeflow 1.8
